import '../globals.css';

import { Inter, Niconne, DM_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import Navbar from '@/components/feature/layout/navbar/navbar';
import { ThemeProvider } from '@/src/theme/ThemeProvider';
import clsx from 'clsx';
import menuItems from '@/src/data/navItem.json';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });
const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='h-full'>
			<body
				className={clsx(
					inter.className,
					dmSans.className,
					'bg-background h-full'
				)}>
				{/* <Navbar appName='X Y' menuItems={menuItems} /> */}
				{children}

				{/* <ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem>
				</ThemeProvider> */}
			</body>
		</html>
	);
}
